# Generated by Django 2.1.7 on 2019-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
